// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv7lHZuKLBTIG6uko5wCDQdgw_XSgeHB0',
    appId: '1:252804690112:web:a013f9160bde3454337d25',
    messagingSenderId: '252804690112',
    projectId: 'quickensol-task',
    authDomain: 'quickensol-task.firebaseapp.com',
    storageBucket: 'quickensol-task.appspot.com',
    measurementId: 'G-JBFV5DB6LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuOCcnSoHJvOGOEQ_GoJoD9-7qNlPO3cE',
    appId: '1:252804690112:android:db0b99d8a0ec34e2337d25',
    messagingSenderId: '252804690112',
    projectId: 'quickensol-task',
    storageBucket: 'quickensol-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjJzXyybuaVSBCTpRpm7SqNoEikUwuQyA',
    appId: '1:252804690112:ios:8357356284445eeb337d25',
    messagingSenderId: '252804690112',
    projectId: 'quickensol-task',
    storageBucket: 'quickensol-task.appspot.com',
    iosBundleId: 'com.example.quickensolTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv7lHZuKLBTIG6uko5wCDQdgw_XSgeHB0',
    appId: '1:252804690112:web:dc3a55e77848102b337d25',
    messagingSenderId: '252804690112',
    projectId: 'quickensol-task',
    authDomain: 'quickensol-task.firebaseapp.com',
    storageBucket: 'quickensol-task.appspot.com',
    measurementId: 'G-21GDMDQPGC',
  );
}
